### ISSUE TITLE
Missing `dselect` and other functions from `dataops.jl`

### ISSUE THREAD

**Issue by smahoff** [LCSB-BioCore/GigaSOM.jl#205]
Versions after 0.6.8 have the majority of functions erased from dataops.jl

Any

**Steps to reproduce**

    1. Install latest GigaSOM
    2. Import distributed dataset
    3. Run dselect

**Expected behavior**
dselect works

**Actual behavior**
dselect won't be found

**Additional information**

**Comment by exaexa** [comment]
Hi! Thanks for pointing this out. The functions weren't erased, but actually moved to a separate, more general package -- you should be able to fix the issue by just importing [`DistributedData.jl`](https://github.com/LCSB-BioCore/DistributedData.jl).

Seeing this issue, I have to say that the change was not announced super-loudly, but we did an [incompatible](https://pkgdocs.julialang.org/v1/compatibility/#compat-pre-1.0) version bump to 0.7 and updated [the docs](https://lcsb-biocore.github.io/GigaSOM.jl/stable/tutorials/distributedProcessing/).

I guess we could improve with highlighting the change a bit more visibly in the main README? (EDIT: at least I pinned this issue so that it's easily visible :] )

(Originally, I was thinking that we could re-export the functions from DistributedData through GigaSOM, but I wanted to avoid namespace pollution and name collisions for people who don't do distributed stuff.)

**Comment by smahoff** [comment]
Thanks for the quick clarification! Just from looking at the GitHub page/install instructions or searching for dselect in the latest version docs/source it wasn't immediately apparent (unless one jumps to tutorial 3). Thanks again!

**Comment by exaexa** [comment]
OK, good that this was indeed the problem -- I was afraid of something more complicated. :D

I'll leave this issue pinned so that others can easily find the solution.
